---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:
          - name: check Banner display
            fetch:
                    src: /etc/ssh/my_banner
                    dest: /tmp/Banner_check
          - name: Get sshd config file
            fetch:
                    src: /etc/ssh/sshd_config
                    dest: /tmp/Banner_check
...
